version: '3'

services:
  test:
    image: devops/test-frontend
    build:
      context: ../
      dockerfile: ./Frontend/test.Dockerfile
    environment:
      - NODE_ENV=test
      - CHROME_BIN=/usr/bin/chromium-browser
