version: '3.3'
services:
  db:
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - my-db:/var/lib/mysql
      - ./SQL/Database_creation.sql:/docker-entrypoint-initdb.d/1.sql
  back:
    image: devops/backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_HOST: '172.17.0.1'
      DB_NAME: 'app'
      TEST_DB_NAME: 'test_db'
      DB_PORT: '3307'
    ports:
      - '3000:3000'
    restart: unless-stopped
  front:
    image: devops/frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - '2000:2000'
    restart: unless-stopped


volumes:
  my-db:

